spring.application.name=tienda-online
server.servlet.context-path=/api

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/tienda_online?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1465
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=coyoteuniformes-super-secret-key-must-be-at-least-256-bits-long!!
jwt.expiration=86400000
